//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PrintCaseInfo2x.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_EXCEPTION_FILE_TYPE_ERROR   101
#define IDS_EXCEPTION_VERSION_LOW       102
#define IDD_MALE_INPUT_VIEW             103
#define IDS_EXCEPTION_CANCEL_OPEN       103
#define IDD_FEMALE_INPUT_VIEW           104
#define IDS_EXCEPTION_LOW_VERSION_FILE  104
#define IDD_PRINTCASEINFOVIEW           105
#define IDR_MAINFRAME                   128
#define IDR_MyTYPE                      129
#define IDD_PASSWORD_DLG                130
#define IDD_CONFIG_DLG                  131
#define IDR_TOOLBAR_ALPHA               133
#define IDD_DOC_EXPORT_DLG              134
#define IDD_DIALOG1                     135
#define IDB_BITMAP_ABOUT                136
#define IDC_BUTTON1                     1000
#define IDC_EDIT_F_EN_POSTALCODE        1001
#define IDC_EDIT_EN_NAME                1001
#define IDC_EDIT_F_EN_AGE               1002
#define IDC_EDIT_F_EN_occupation        1003
#define IDC_EDIT_EN_AGE                 1003
#define IDC_EDIT_F_EN_KNOWLEDGE_DEGREE  1004
#define IDC_EDIT_F_EN_NATION            1005
#define IDC_EDIT_EN_PHONE               1005
#define IDC_EDIT_F_ZHEN_DUAN            1006
#define IDC_EDIT_EN_OCCUPATION          1006
#define IDC_EDIT_F_ZHU_SU               1007
#define IDC_EDIT_EN_KNOWLEDGE_DEGREE    1007
#define IDC_EDIT_F_XIAN_BING_SHI        1008
#define IDC_EDIT_MI_NIAO_SHENG_ZHI      1008
#define IDC_EDIT_F_EN_PHONE             1009
#define IDC_COMBO_XIN_XUE_GUAN          1009
#define IDC_EDIT_F_EN_FSH               1010
#define IDC_COMBO_MI_NIAO_SHENG_ZHI     1010
#define IDC_EDIT_C_ZHEN_LIAO_JI_HUA     1011
#define IDC_COMBO_XING_CHUAN_BO         1011
#define IDC_EDIT_F_CS_SHOU_SHU_SHI      1012
#define IDC_COMBO_JIE_HE                1012
#define IDC_EDIT_F_JI_WANG_QI_TA        1013
#define IDC_COMBO_GAN_YAN               1013
#define IDC_EDIT_C_BING_LI_TE_DIAN      1014
#define IDC_COMBO_XI_YAN                1014
#define IDC_EDIT_F_CS_YAO_WU_GUO_MIN    1015
#define IDC_EDIT_XI_YAN                 1015
#define IDC_EDIT_F_CI_XI_YAN            1016
#define IDC_COMBO_F_JI_WANG_GAN_YAN     1017
#define IDC_COMBO_F_JIE_HE              1018
#define IDC_COMBO_CS_YAO_WU_GUO_MIN     1018
#define IDC_COMBO_F_SHEN_ZANG_JI_BING   1019
#define IDC_COMBO_CS_CHU_SHENG_QUE_XIAN 1019
#define IDC_COMBO_F_XIN_XUE_GUAN_JI_BING 1020
#define IDC_EDIT_EN_NATION              1020
#define IDC_COMBO_F_MI_NIAO_XI_TONG_GAN_RAN 1021
#define IDC_COMBO_F_XING_CHUAN_BO_JI_BING_SHI 1022
#define IDC_EDIT_EN_ADDRESS             1022
#define IDC_COMBO_F_LAN_WEI_YAN         1023
#define IDC_EDIT_EN_COMPANY             1023
#define IDC_COMBO_F_PEN_QIANG_YAN       1024
#define IDC_EDIT_ZHU_SU                 1024
#define IDC_COMBO_F_CS_SHOU_SHU_SHI     1025
#define IDC_COMBO_F_TING_JING           1026
#define IDC_EDIT_XIAN_BING_SHI          1026
#define IDC_COMBO_JIN_QING_JIE_HUN      1027
#define IDC_COMBO_ZAI_HUN               1028
#define IDC_COMBO_F_CS_YAO_WU_GUO_MIN   1029
#define IDC_COMBO_F_CI_XI_YAN           1030
#define IDC_COMBO_F_JING_LIANG          1031
#define IDC_COMBO_CS_YI_CHUAN_BING_SHI  1031
#define IDC_EDIT_JIAN_KANG_ZHUANG_KUANG_GUO_QU 1032
#define IDC_EDIT_SHENG_ZHI_QI_TA        1033
#define IDC_COMBO_F_XI_DU               1034
#define IDC_COMBO_F_XU_JIU              1035
#define IDC_EDIT_F_YUE_JING_SHI_YUE_JING_ZHOU_QI1 1036
#define IDC_EDIT_F_CHU_CHAO             1037
#define IDC_EDIT_F_CS_JIAN_KANG_ZHUANG_KUANG 1038
#define IDC_EDIT_JI_WANG_BING_SHI_QI_TA 1038
#define IDC_COMBO_F_ZHONG_DA_JING_SHEN_CI_JI 1039
#define IDC_EDIT_JIAN_KANG_ZHUANG_KUANG_XIAN_ZAI 1039
#define IDC_EDIT_F_CS_CHU_SHENG_QUE_XIAN 1040
#define IDC_EDIT_JIN_YU_TIAN_SHU        1040
#define IDC_COMBO_F_CS_CHU_SHENG_QUE_XIAN 1041
#define IDC_EDIT_F_MO_CI_YUE_JING       1042
#define IDC_COMBO_F_JIN_QIN_JIE_HUN     1043
#define IDC_COMBO_CS_BU_YUN_BU_YU       1043
#define IDC_COMBO_F_ZAI_HUN             1044
#define IDC_COMBO_XU_JIU                1044
#define IDC_COMBO_F_REN_CHEN            1045
#define IDC_COMBO_ZHONG_DA_JING_SHENG_CI_JI 1045
#define IDC_EDIT_F_MO_CI_REN_CHEN       1046
#define IDC_COMB_HU_XU                  1046
#define IDC_EDIT_F_YUN                  1047
#define IDC_COMB_HOU_JIE                1047
#define IDC_EDIT_F_CHAN                 1048
#define IDC_COMBO_CS_RU_FANG            1048
#define IDC_EDIT_F_REN_GONG_LIU_CHAN    1049
#define IDC_COMB_CS_YIN_JING            1049
#define IDC_EDIT_F_ZI_RAN_LIU_CHAN      1050
#define IDC_EDIT_CS_YIN_JING            1050
#define IDC_EDIT_F_YAO_LIU              1051
#define IDC_EDIT_XUE_YA_1               1051
#define IDC_EDIT_F_YIN_CHAN             1052
#define IDC_EDIT_CS_YAO_WU_GUO_MIN      1052
#define IDC_EDIT_F_ZAO_CHAN             1053
#define IDC_EDIT_CS_CHU_SHENG_QUE_XIAN  1053
#define IDC_EDIT_F_GONG_WAI_YUAN_ZUO    1054
#define IDC_EDIT_XUE_YA_2               1054
#define IDC_EDIT_F_GONG_WAI_YUAN_YOU    1055
#define IDC_EDIT_SHENG_ZHI_JI_SU        1055
#define IDC_EDIT_F_ZU_CHAN_YUE          1056
#define IDC_EDIT_CS_YI_CHUAN_BING_SHI   1056
#define IDC_EDIT_F_EN_NAME              1057
#define IDC_EDIT_CS_BU_YUN_BU_YU        1057
#define IDC_EDIT_F_XIAN_YOU_ZI_NV       1058
#define IDC_EDIT_TI_ZHONG               1058
#define IDC_EDIT_F_EN_ADDRESS           1059
#define IDC_EDIT_SHEN_GAO               1059
#define IDC_EDIT_F_EN_COMPANY           1060
#define IDC_EDIT_F_EN_IDENTITY_CARD     1061
#define IDC_EDIT_GAO_WAN_TI_JI_ZUO      1061
#define IDC_EDIT_F_CS_BU_YUN_BU_YU_SHI  1062
#define IDC_COMBO_F_CS_BU_YUN_BU_YU_SHI 1063
#define IDC_EDIT_GAO_WAN_TI_JI_YOU      1063
#define IDC_EDIT_F_CS_YI_CHUAN_BING_SHI 1064
#define IDC_COMBO_CS_GAO_WAN_ZHI_DI_ZUO 1064
#define IDC_COMBO_F_CS_YI_CHUAN_BING_SHI 1065
#define IDC_EDIT_CS_GAO_WAN_ZHI_DI_ZUO  1065
#define IDC_EDIT_F_YI_BAN_QING_KUANG_T  1066
#define IDC_COMBO_CS_GAO_WAN_ZHI_DI_YOU 1066
#define IDC_EDIT_F_YI_BAN_QING_KUANG_P  1067
#define IDC_EDIT_CS_GAO_WAN_ZHI_DI_YOU  1067
#define IDC_EDIT_F_YI_BAN_QING_KUANG_R  1068
#define IDC_COMBO_CS_FU_GAO_ZUO         1068
#define IDC_EDIT_F_YI_BAN_QING_KUANG_BP1 1069
#define IDC_EDIT_CS_FU_GAO_ZUO          1069
#define IDC_EDIT_F_SHEN_GAO             1070
#define IDC_COMBO_CS_FU_GAO_YOU         1070
#define IDC_EDIT_F_TI_ZHONG             1071
#define IDC_EDIT_CS_FU_GAO_YOU          1071
#define IDC_EDIT_F_CS_FA_YU             1072
#define IDC_COMBO_CS_SHU_JING_GUAN_ZUO  1072
#define IDC_COMBO_F_CS_FA_YU            1073
#define IDC_EDIT_CS_SHU_JING_GUAN_ZUO   1073
#define IDC_EDIT_F_CS_YING_YANG         1074
#define IDC_COMBO_YIN_MAO               1074
#define IDC_COMBO_F_CS_YING_YANG        1075
#define IDC_COMBO_CS_SHU_JING_GUAN_YOU  1075
#define IDC_EDIT_F_CS_MAO_FA            1076
#define IDC_EDIT_CS_SHU_JING_GUAN_YOU   1076
#define IDC_COMBO_F_CS_MAO_FA           1077
#define IDC_COMBO_CS_JING_SUO_JING_MAI_ZUO 1077
#define IDC_EDIT_F_CS_JING_SHEN         1078
#define IDC_EDIT_CS_JING_SUO_JING_MAI_ZUO 1078
#define IDC_COMBO_F_CS_JING_SHEN        1079
#define IDC_COMBO_CS_JING_SUO_JING_MAI_YOU 1079
#define IDC_EDIT_F_CS_LIN_BA_JIE        1080
#define IDC_EDIT_CS_JING_SUO_JING_MAI_YOU 1080
#define IDC_COMBO_F_CS_LIN_BA_JIE       1081
#define IDC_EDIT_JING_YE_LIANG          1081
#define IDC_EDIT_F_CS_PI_FU_NIAN_MO     1082
#define IDC_EDIT_EN_PH                  1082
#define IDC_COMBO_F_CS_PI_FU_NIAN_MO    1083
#define IDC_EDIT_YE_HUA_SHI_JIAN        1083
#define IDC_COMBO_F_CS_JIAN_KANG_ZHUANG_KUANG 1084
#define IDC_EDIT_MI_DU                  1084
#define IDC_COMBO_F_CS_YI_RU            1085
#define IDC_EDIT_HUO_LI_A_JI            1085
#define IDC_EDIT_F_CS_RU_FANG           1086
#define IDC_EDIT_HUO_LI_B_JI            1086
#define IDC_COMBO_F_CS_RU_FANG          1087
#define IDC_EDIT_HUO_LI_C_JI            1087
#define IDC_EDIT_F_CS_FEI               1088
#define IDC_EDIT_HUO_LI_D_JI            1088
#define IDC_COMBO_F_CS_FEI              1089
#define IDC_EDIT_ZHENG_CHANG_XING_TAI_LV 1089
#define IDC_EDIT_F_CS_XIN               1090
#define IDC_EDIT_BAI_XI_BAO             1090
#define IDC_COMBO_F_CS_XIN              1091
#define IDC_COMBO_XUE_XING              1091
#define IDC_EDIT_F_CS_PI                1092
#define IDC_COMBO_F_CS_PI               1093
#define IDC_COMBO_RH_YIN_ZI             1093
#define IDC_EDIT_F_CS_GAN               1094
#define IDC_COMBO_LIN_QIU_JUN           1094
#define IDC_COMBO_F_CS_GAN              1095
#define IDC_COMBO_ZHI_YUAN_TI           1095
#define IDC_EDIT_F_CS_JI_ZHU_SI_ZHI     1096
#define IDC_COMBO_YI_YUAN_TI            1096
#define IDC_COMBO_F_CS_JI_ZHU_SI_ZHI    1097
#define IDC_EDIT_F_CS_SHEN              1098
#define IDC_COMBO_GAN_YAN_GAN_YAN       1098
#define IDC_COMBO_F_CS_SHEN             1099
#define IDC_EDIT_F_CS_YIN_DAO           1100
#define IDC_EDIT_YI_CHUAN_XUE_JIAN_CHA  1100
#define IDC_COMBO_F_CS_YIN_DAO          1101
#define IDC_EDIT_CHU_BU_ZHEN_DUAN       1101
#define IDC_EDIT_F_CS_WAI_YIN           1102
#define IDC_COMBO_GAN_YAN_HIV           1102
#define IDC_COMBO_F_CS_WAI_YIN          1103
#define IDC_EDIT_NAN_YI_SHI             1103
#define IDC_EDIT_F_GONG_JING_JIAN_CHA   1104
#define IDC_COMBO_F_CS_GONG_JING_MORE   1105
#define IDC_COMBO_F_CS_GONG_JING        1107
#define IDC_EDIT_F_CS_ZI_GONG_DA_XIAO   1108
#define IDC_COMBO_F_CS_ZI_GONG_DA_XIAO  1109
#define IDC_EDIT_F_YI_BAN_QING_KUANG_BP2 1110
#define IDC_COMBO_F_ZI_GONG             1111
#define IDC_COMBO_F_ZHI_DI              1112
#define IDC_COMBO_F_HUO_DONG_DU         1113
#define IDC_COMBO_F_YA_TONG             1114
#define IDC_EDIT_F_CS_FU_JIAN_YOU       1115
#define IDC_COMBO_F_CS_FU_JIAN_YOU      1116
#define IDC_EDIT_F_CS_FU_JIAN_ZUO       1117
#define IDC_COMBO_F_CS_FU_JIAN_ZUO      1118
#define IDC_EDIT_F_EN_E_2               1123
#define IDC_EDIT_F_EN_P                 1124
#define IDC_EDIT_F_EN_LH                1125
#define IDC_EDIT_F_EN_PRL               1126
#define IDC_EDIT_F_EN_T                 1127
#define IDC_EDIT_F_RAN_SE_TI            1140
#define IDC_EDIT_F_GONG_JING_GUA_PIAN   1141
#define IDC_EDIT_F_ZHENG_LIAO_JI_HUA    1143
#define IDC_EDIT_F_NV_YI_SHI            1144
#define IDC_EDIT_F_FU_KE_B_CHAO_RI_QI   1146
#define IDC_COMBO_F_QING_JIE_DU         1147
#define IDC_COMBO_FU_KE_ZI_GONG_LEI_XING 1148
#define IDC_COMBO_F_XUE_CHANG_GUI       1149
#define IDC_COMB_F_NIAO_CHANG_GUI       1150
#define IDC_EDIT_F_FU_KE_ZI_GONG_NEI_MO 1151
#define IDC_EDIT_F_YOU_CE_LUAN_CHAO     1152
#define IDC_EDIT_F_ZUO_CE_LUAN_CHAO     1153
#define IDC_EDIT_F_GONG_QIANG_JING      1154
#define IDC_EDIT_F_YUE_JING_ZHOU_QI1    1156
#define IDC_EDIT_F_LUAN_PAO_ZHI_JING1   1157
#define IDC_EDIT_F_ZI_GONG_NEI_MO1      1158
#define IDC_EDIT_F_BING_SHI_XIAO_JIE    1159
#define IDC_EDIT_F_FU_KE_ZI_GONG_DA_XIAO 1160
#define IDC_EDIT_F_ZI_GONG_XING_TAI     1167
#define IDC_EDIT_F_ZUO_CE_SHU_LUAN_GUAN 1168
#define IDC_EDIT_F_YOU_CE_SHU_LUAN_GUAN 1169
#define IDC_COMBO_F_XUE_XING            1170
#define IDC_COMBO_F_RH_YIN_ZI           1171
#define IDC_COMBO_F_GONG_XING_CHONG     1172
#define IDC_COMBO_F_JU_XI_BAO_BING_DU   1173
#define IDC_EDIT_CS_RU_FANG             1173
#define IDC_EDIT_F_YUE_JING_ZHOU_QI2    1174
#define IDC_EDIT_F_LUAN_PAO_ZHI_JING2   1175
#define IDC_DATETIMEPICKER_F_DATE_LUO_KUAN 1176
#define IDC_DATETIMEPICKER_C_DATE_YE_MEI 1177
#define IDC_DATETIMEPICKER_DATE_JING_YE_FEN_XI 1177
#define IDC_EDIT_C_BING_LI_HAO          1178
#define IDC_DATETIMEPICKER_DATE_LUO_KUAN 1179
#define IDC_DATETIMEPICKER_DATE_CHU_ZHEN 1180
#define IDC_EDIT_C_NI_XING_AIH_FANG_SHI 1181
#define IDC_EDIT_F_ZI_GONG_NEI_MO2      1182
#define IDC_EDIT_F_YUE_JING_ZHOU_QI3    1184
#define IDC_EDIT_F_LUAN_PAO_ZHI_JING3   1185
#define IDC_EDIT_F_ZI_GONG_NEI_MO3      1186
#define IDC_EDIT_F_YUE_JING_ZHOU_QI4    1188
#define IDC_EDIT_F_LUAN_PAO_ZHI_JING4   1189
#define IDC_EDIT_F_ZI_GONG_NEI_MO4      1190
#define IDC_COMBO_F_FENG_ZHEN_BING_DU   1191
#define IDC_COMBO_F_DAN_CHUN_PAO_ZHEN_BING_DU_II_XING 1192
#define IDC_COMBO_F_EN_HBSAG            1193
#define IDC_COMBO_F_EN_HBEAB            1194
#define IDC_COMBO_F_EN_HCVAB            1195
#define IDC_COMBO_F_EN_HBSAB            1196
#define IDC_COMBO_F_EN_HBCAB            1197
#define IDC_COMBO_F_EN_HCVAG            1198
#define IDC_COMBO_F_EN_HBEAG            1199
#define IDC_COMBO_F_EN_HAV_I            1200
#define IDC_COMBO_F_EN_HIVAB            1201
#define IDC_COMBO_F_KANG_ZI_GONG_NEI_MO_KANG_TI 1202
#define IDC_COMBO_F_KANG_LUAN_CHAO_KANG_TI 1203
#define IDC_COMBO_F_KANG_TOU_MING_DAI_KANG_TI 1204
#define IDC_COMBO_F_KANG_JING_ZI_KANG_TI 1205
#define IDC_COMBO_F_GAN_GONG            1206
#define IDC_COMBO_F_SHEN_GONG           1207
#define IDC_COMBO_F_ZHI_YUAN_TI         1208
#define IDC_COMBO_F_YI_YUAN_TI          1209
#define IDC_COMBO_F_DI_CHONG            1210
#define IDC_COMBO_F_MEI_JUN             1211
#define IDC_COMBO_F_XIAN_SUO_XI_BAO     1212
#define IDC_DATETIMEPICKER_C_DATE_SHOU_CI_BING_CHENG_JI_LU 1213
#define IDC_EDIT_C_FU_HE_AIH_ZHI_ZHENG  1214
#define IDC_EDIT_C_JIN_JI_ZHENG         1215
#define IDC_EDIT_C_NI_XING_ZHI_LIAO_FANG_AN 1216
#define IDC_EDIT_C_FU_ZHU_JIAN_CHA_YI_CHANG_JIE_GUO 1217
#define IDC_EDIT_C_BING_CHENG_JI_LU_QI_TA 1218
#define IDC_EDIT_C_BING_CHENG_JI_LU_YI_SHI 1219
#define IDC_EDIT_F_PAI_LUAN_JIAN_CE1    1221
#define IDC_EDIT_F_PAI_LUAN_JIAN_CE2    1222
#define IDC_EDIT_F_PAI_LUAN_JIAN_CE3    1223
#define IDC_EDIT_F_PAI_LUAN_JIAN_CE4    1224
#define IDC_EDIT_F_YOU_CE_LUAN_CHAO_FC  1235
#define IDC_STATIC_SCRIPT               1237
#define IDC_EDIT_EN_IDENTITY_CARD       1328
#define IDC_EDIT_F_YUE_JING_SHI_YUE_JING_ZHOU_QI2 1329
#define IDC_EDIT_F_ZUO_CE_LUAN_CHAO_FC  1330
#define IDC_EDIT_PASSWORD               1331
#define IDC_STATIC_MESSAGE              1332
#define IDC_COMBO_STYTLE                1332
#define IDC_COMBO_VIEW                  1333
#define IDC_PROGRESS1                   1333
#define IDC_OPEN_WORD                   1334
#define IDC_STATIC_MSG                  1335
#define IDC_PREVIEW_WORD                1336
#define IDC_BUTTON3                     1337
#define IDC_SAVE_WORD                   1337
#define IDC_STATIC_BLOG                 1339
#define IDC_STATIC_QQ                   1339
#define IDC_STATIC_BMP                  1340
#define IDC_STATIC_BLOG2                1340
#define IDC_STATIC_GMAIL                1340
#define IDC_STATIC_VERSION              1341
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_MENU_MALE_VIEW               32773
#define ID_MENU_FEMALE_VIEW             32774
#define ID_32775                        32775
#define ID_EXPORT_TO_WORD               32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_MENU_FILE_LOCK               32779
#define ID_MENU_DEL_FILE_LOCK           32780
#define ID_32782                        32782
#define ID_SOFT_CONFIG                  32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1342
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
